# Generated by Django 4.2.7 on 2023-11-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
                ('Vehicle Type', models.CharField(max_length=50)),
                ('Brand', models.CharField(max_length=50)),
                ('Model', models.CharField(max_length=50)),
                ('Year', models.DateField()),
                ('Kilometers', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=20)),
                ('Number of Owners', models.IntegerField()),
                ('Price (INR)', models.IntegerField()),
                ('Payment Option', models.CharField(max_length=50)),
                ('Photos (optional)', models.ImageField(upload_to='photos')),
            ],
        ),
    ]
